// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lobbies.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createLobby = `-- name: CreateLobby :one
INSERT INTO lobbies (id, lobby_name, game_master, short_description, game_map, created_at, updated_at)
VALUES (
  gen_random_uuid(),
  $1,
  $2,
  $3,
  NULL,
  NOW(),
  NOW()
)
RETURNING id, lobby_name, game_master, short_description, game_map, created_at, updated_at
`

type CreateLobbyParams struct {
	LobbyName        string
	GameMaster       uuid.UUID
	ShortDescription sql.NullString
}

func (q *Queries) CreateLobby(ctx context.Context, arg CreateLobbyParams) (Lobby, error) {
	row := q.db.QueryRowContext(ctx, createLobby, arg.LobbyName, arg.GameMaster, arg.ShortDescription)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.LobbyName,
		&i.GameMaster,
		&i.ShortDescription,
		&i.GameMap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllLobbies = `-- name: DeleteAllLobbies :exec
DELETE FROM lobbies
`

func (q *Queries) DeleteAllLobbies(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllLobbies)
	return err
}

const deleteLobbyByName = `-- name: DeleteLobbyByName :exec
DELETE FROM lobbies
WHERE lobby_name = $1
`

func (q *Queries) DeleteLobbyByName(ctx context.Context, lobbyName string) error {
	_, err := q.db.ExecContext(ctx, deleteLobbyByName, lobbyName)
	return err
}

const getLobbyById = `-- name: GetLobbyById :one
SELECT id, lobby_name, game_master, short_description, game_map, created_at, updated_at FROM lobbies
WHERE id = $1
`

func (q *Queries) GetLobbyById(ctx context.Context, id uuid.UUID) (Lobby, error) {
	row := q.db.QueryRowContext(ctx, getLobbyById, id)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.LobbyName,
		&i.GameMaster,
		&i.ShortDescription,
		&i.GameMap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLobbyIDByName = `-- name: GetLobbyIDByName :one
SELECT id, lobby_name, game_master, short_description, game_map, created_at, updated_at FROM lobbies
WHERE lobby_name = $1
`

func (q *Queries) GetLobbyIDByName(ctx context.Context, lobbyName string) (Lobby, error) {
	row := q.db.QueryRowContext(ctx, getLobbyIDByName, lobbyName)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.LobbyName,
		&i.GameMaster,
		&i.ShortDescription,
		&i.GameMap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
