// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lobbies_players.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getLobbyPlayers = `-- name: GetLobbyPlayers :many
SELECT users.id, users.email, users.google_id, users.username, users.avatar_url, users.created_at, users.updated_at, users.hashed_password, users.is_chirpy_red
FROM users
JOIN lobbies_players
ON users.id = lobbies_players.player_id
WHERE lobbies_players.lobby_id = $1
`

func (q *Queries) GetLobbyPlayers(ctx context.Context, lobbyID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getLobbyPlayers, lobbyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.GoogleID,
			&i.Username,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HashedPassword,
			&i.IsChirpyRed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerLobbies = `-- name: GetPlayerLobbies :many
SELECT lobbies.id, lobbies.lobby_name, lobbies.game_master, lobbies.short_description, lobbies.game_map, lobbies.created_at, lobbies.updated_at
FROM lobbies
JOIN lobbies_players
ON lobbies.id = lobbies_players.lobby_id
WHERE lobbies_players.player_id = $1
`

func (q *Queries) GetPlayerLobbies(ctx context.Context, playerID uuid.UUID) ([]Lobby, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerLobbies, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lobby
	for rows.Next() {
		var i Lobby
		if err := rows.Scan(
			&i.ID,
			&i.LobbyName,
			&i.GameMaster,
			&i.ShortDescription,
			&i.GameMap,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinLobby = `-- name: JoinLobby :exec
INSERT INTO lobbies_players (lobby_id, player_id)
VALUES (
  $1,
  $2
)
`

type JoinLobbyParams struct {
	LobbyID  uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) JoinLobby(ctx context.Context, arg JoinLobbyParams) error {
	_, err := q.db.ExecContext(ctx, joinLobby, arg.LobbyID, arg.PlayerID)
	return err
}

const leaveLobby = `-- name: LeaveLobby :exec
DELETE FROM lobbies_players
WHERE lobby_id = $1
AND player_id = $2
`

type LeaveLobbyParams struct {
	LobbyID  uuid.UUID
	PlayerID uuid.UUID
}

func (q *Queries) LeaveLobby(ctx context.Context, arg LeaveLobbyParams) error {
	_, err := q.db.ExecContext(ctx, leaveLobby, arg.LobbyID, arg.PlayerID)
	return err
}
