// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Chirp struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    uuid.UUID
}

type LobbiesPlayer struct {
	LobbyID  uuid.UUID
	PlayerID uuid.UUID
	JoinedAt time.Time
}

type Lobby struct {
	ID               uuid.UUID
	LobbyName        string
	GameMaster       uuid.UUID
	ShortDescription sql.NullString
	GameMap          sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Email          string
	GoogleID       sql.NullString
	Username       string
	AvatarUrl      sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
	IsChirpyRed    bool
}
