// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (id, email, google_id, username, avatar_url, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    NOW(),
    NOW()
)
RETURNING id, email, google_id, username, avatar_url, created_at, updated_at, hashed_password, is_chirpy_red
`

type CreateGoogleUserParams struct {
	Email     string
	GoogleID  sql.NullString
	Username  string
	AvatarUrl sql.NullString
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createGoogleUser,
		arg.Email,
		arg.GoogleID,
		arg.Username,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, google_id, username, hashed_password, avatar_url, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    null,
    $2,
    $3,
    null,
    NOW(),
    NOW()
)
RETURNING id, email, google_id, username, avatar_url, created_at, updated_at, hashed_password, is_chirpy_red
`

type CreateUserParams struct {
	Email          string
	Username       string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Username, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsers)
	return err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id, email, google_id, username, avatar_url, created_at, updated_at, hashed_password, is_chirpy_red FROM users
WHERE email = $1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Username,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const userUpdatePassword = `-- name: UserUpdatePassword :exec
UPDATE users
SET
  updated_at = NOW(),
  hashed_password = $2
WHERE id = $1
`

type UserUpdatePasswordParams struct {
	ID             uuid.UUID
	HashedPassword string
}

func (q *Queries) UserUpdatePassword(ctx context.Context, arg UserUpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, userUpdatePassword, arg.ID, arg.HashedPassword)
	return err
}

const userUpgradeToChirpRed = `-- name: UserUpgradeToChirpRed :exec
UPDATE users
SET
  updated_at = NOW(),
  is_chirpy_red = TRUE
WHERE id = $1
`

func (q *Queries) UserUpgradeToChirpRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, userUpgradeToChirpRed, id)
	return err
}
